"""Initial migration

Revision ID: 33960a499ae7
Revises:
Create Date: 2026-01-03 18:51:25.438961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33960a499ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(), nullable=False),
    sa.Column('clock_out_time', sa.DateTime(), nullable=True),
    sa.Column('approved_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('estimated_loss',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_log_farmer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('pay_rate', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pay_rate')
        batch_op.drop_column('position')

    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_log_farmer_id_fkey'), 'farmer', ['farmer_id'], ['id'])

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('estimated_loss',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheets_user_id'))

    op.drop_table('timesheets')
    # ### end Alembic commands ###
