"""Add payout_requests to InsuranceRate

Revision ID: 3f779678abb2
Revises: c1745125605e
Create Date: 2025-07-24 15:59:57.114162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f779678abb2'
down_revision = 'c1745125605e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_requests', sa.Integer(), nullable=True))

    op.execute("UPDATE insurance_rates SET payout_requests = 0")

    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.alter_column('payout_requests', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.drop_column('payout_requests')

    # ### end Alembic commands ###
