"""Remove vehicle_locations table

Revision ID: 402f6320fd0c
Revises: b695bb7eccaa
Create Date: 2026-03-16 22:56:26.351006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '402f6320fd0c'
down_revision = 'b695bb7eccaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_user_id'))

    op.drop_table('vehicle_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vehicle_locations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_locations_pkey'))
    )
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_locations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_locations_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###
