"""Add InsuranceRate model

Revision ID: 42f3b5903c66
Revises: fe45aecdf1fc
Create Date: 2025-07-24 00:51:32.971141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f3b5903c66'
down_revision = 'fe45aecdf1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_rates')
    # ### end Alembic commands ###
