"""Initial migration

Revision ID: 90e089e3b246
Revises:
Create Date: 2026-01-07 02:40:49.169568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90e089e3b246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_clocked_in', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('last_clock_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_session_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_session_start')
        batch_op.drop_column('last_clock_in')
        batch_op.drop_column('is_clocked_in')
    # ### end Alembic commands ###
