"""Add Vehicle model

Revision ID: b695bb7eccaa
Revises: bc9e8f8c1f6e
Create Date: 2026-01-08 04:15:51.953016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b695bb7eccaa'
down_revision = 'bc9e8f8c1f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_locations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_locations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_timestamp'))

    op.drop_table('vehicle_locations')
    # ### end Alembic commands ###
