"""Add StoreItem model

Revision ID: bc9e8f8c1f6e
Revises: 0353c1665eff
Create Date: 2026-01-07 23:56:21.227133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc9e8f8c1f6e'
down_revision = '0353c1665eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('xml_filename', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_items_xml_filename'), ['xml_filename'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_items_xml_filename'))

    op.drop_table('store_items')
    # ### end Alembic commands ###
