"""Add rate_type to InsuranceRate

Revision ID: c1745125605e
Revises: 42f3b5903c66
Create Date: 2025-07-24 15:29:09.208658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1745125605e'
down_revision = '42f3b5903c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_type', sa.Enum('VEHICLE', 'FARM', 'CROP', 'ANIMAL', name='insuranceratetype'), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    op.execute("UPDATE insurance_rates SET name = vehicle_type, rate_type = 'VEHICLE'")

    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)
        batch_op.alter_column('rate_type', nullable=False)
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('rate_type')

    # ### end Alembic commands ###
