"""Rename created_at to application_date

Revision ID: ea8eae891d90
Revises: d26f453da33f
Create Date: 2025-07-09 11:00:51.443346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea8eae891d90'
down_revision = 'd26f453da33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permit_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permit_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('application_date')

    # ### end Alembic commands ###
